# Generated by Django 4.2.23 on 2025-09-07 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_status_inventoryitem_invoice_number_kititem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KitItem',
        ),
    ]
