# Generated by Django 4.2.23 on 2025-09-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_delete_kititem'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
