# Generated by Django 4.2.23 on 2025-09-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventoryitem_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
