# Generated by Django 4.2 on 2025-07-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_inventoryitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='image',
            field=models.ImageField(blank=True, default='inventory_images/default_inventory.png', null=True, upload_to='inventory_images/'),
        ),
    ]
