# Generated by Django 4.2 on 2025-07-14 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_inventoryitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='document',
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='item_documents/')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='inventory.inventoryitem')),
            ],
        ),
    ]
