# Generated by Django 4.2 on 2025-07-15 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0013_remove_inventoryitem_document_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorylog',
            old_name='item',
            new_name='inventory_item',
        ),
        migrations.RenameField(
            model_name='inventorylog',
            old_name='uid_no',
            new_name='uid_number',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='description',
            new_name='address',
        ),
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('LAP', 'Laptop'), ('MON', 'Monitor'), ('KBD', 'Keyboard'), ('MSE', 'Mouse'), ('DOCK', 'Docking Station'), ('HDS', 'Headset'), ('PRN', 'Printer'), ('SRV', 'Server'), ('NET', 'Network Device'), ('STG', 'Storage Device'), ('SW', 'Software'), ('OTH', 'Other')], default='OTH', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('in_repair', 'In Repair'), ('disposed', 'Disposed'), ('missing', 'Missing'), ('damaged', 'Damaged')], default='available', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='action',
            field=models.CharField(choices=[('added', 'Added'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('transferred', 'Transferred'), ('status_checked', 'Status Checked'), ('status_change', 'Status Change'), ('assigned_to_project', 'Assigned to Project'), ('unassigned_from_project', 'Unassigned from Project'), ('location_change', 'Location Change'), ('login', 'User Login'), ('logout', 'User Logout'), ('login_failed', 'Login Failed'), ('register', 'User Registered'), ('deletion_failed', 'Deletion Failed'), ('quantity_reduced', 'Quantity Reduced'), ('transfer_lookup_failed', 'Transfer Lookup Failed'), ('modify_lookup_failed', 'Modify Lookup Failed'), ('document_added', 'Document Added'), ('document_deleted', 'Document Deleted'), ('document_deletion_failed', 'Document Deletion Failed'), ('export_excel', 'Exported Excel'), ('export_transfer_excel', 'Exported Transfer Log'), ('export_all_logs_excel', 'Exported All Logs')], max_length=50),
        ),
    ]
