# Generated by Django 4.2 on 2025-07-15 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_rename_item_inventorylog_inventory_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='item_direct_documents/', verbose_name='Associated Document'),
        ),
    ]
