# Generated by Django 4.2 on 2025-07-15 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_inventoryitem_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='document_file',
        ),
    ]
