# Generated by Django 5.2.4 on 2025-07-19 03:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_remove_inventoryitem_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
