# Generated by Django 4.2 on 2025-07-28 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_inventoryitem_date_added_inventoryitem_last_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Laptop, Monitor, Server', max_length=100, unique=True)),
                ('prefix', models.CharField(help_text='Short prefix for UID (e.g., LAP, MON, SRV)', max_length=10, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Item Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['item_name'], 'verbose_name_plural': 'Inventory Items'},
        ),
        migrations.AlterModelOptions(
            name='inventorylog',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Inventory Logs'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='inventorylog',
            name='new_value',
        ),
        migrations.RemoveField(
            model_name='inventorylog',
            name='old_value',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='last_transfer_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='cpu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='gpu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='inventory_images/'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='installed_software',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='os',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('in_repair', 'In Repair'), ('retired', 'Retired'), ('lost', 'Lost')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='uid_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='action',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='details',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='uid_number',
            field=models.CharField(blank=True, help_text='UID of the item at the time of log', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uidcategorysequence',
            name='category_prefix',
            field=models.CharField(help_text='Matches ItemCategory prefix', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='uidcategorysequence',
            name='last_sequence_number',
            field=models.IntegerField(default=0, help_text='Last sequence number used for this category and month'),
        ),
        migrations.AlterField(
            model_name='uidcategorysequence',
            name='year_month',
            field=models.CharField(help_text='Format YYMM, e.g., 2312 for Dec 2023', max_length=4),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.itemcategory'),
        ),
    ]
