# Generated by Django 4.2 on 2025-08-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_itemcategory_alter_inventoryitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('Offline', 'Offline'), ('Online', 'Online'), ('Assigned', 'Assigned'), ('In Transit', 'In Transit')], default='available', max_length=20),
        ),
    ]
